### ISSUE TITLE
Could not load type "sonata_formatter_type" 

### ISSUE THREAD

**Issue by KunwarSiddharthSingh** [sonata-project/ecommerce#19]
When I create a Product type through command line 

```
php app/console sonata:product:generate Bowl  sonata.ecommerce_demo.product.bowl
```

And configured all services and go admin panel and click "sonata.ecommerce_demo.product.bowl" then show me error:

```
 Could not load type "sonata_formatter_type"
```

Why ?

**Comment by blaues0cke** [comment]
After a lot of struggling: You have to install IvoryCKEditorBundle (https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/installation.md).

Otherwhise the formatter will not be loaded, see:

    if (isset($bundles['IvoryCKEditorBundle'])) {
        $loader->load('form.xml');
    }

**Comment by Siddharth22** [comment]
@blaues0cke Thanks !
