### ISSUE TITLE
Moving twig templates from [BasketBundle] to [ProductBundle] ?

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/ecommerce#235]
Is it possible to move the add_product_form.html.twig and add_product_poppin.html.twig from the [BasketBundle] to the [ProductBundle] so as to make them easily extendable on a by product base, like the form_basket_element.html.twig and final_review_basket_element.html.twig ? Thanks.

**Comment by jordisala1991** [comment]
Can find those files on 2.x on the basketBundle.

Closing for now. If you think this issue is still relevant, please ping me to reopen.
