### ISSUE TITLE
Problem when adding a basket trough the API

### ISSUE THREAD

**Issue by grosenbaum** [sonata-project/ecommerce#252]
Steps to reproduce:
- Using a fresh install of the sandbox
- Connected as _admin_ / _admin_ in /api/doc
- Trying to POST a basket rises a _500 Internal Server Error_

**Comment by utilisezlinux** [comment]
try a POST in /api/ecommerce…

You can see the params in routing_api.yml
```
sonata_api_ecommerce_basket:
    type:         rest
    prefix:       /ecommerce
    resource:     "@SonataBasketBundle/Resources/config/routing/api.xml"
```

**Comment by utilisezlinux** [comment]
I personally have an api issue just in getting a product through /app_dev.php/api/ecommerce/products/528, I have the following error in both navigator and curl : No matching accepted Response format could be determined, while handling: Format '' not supported, handler must be implemented.

I can't find where to set this format so that it is not empty…

**Comment by Bladrak** [comment]
@utilisezlinux try to append .json at the end of the URL.

**Comment by utilisezlinux** [comment]
@Bladrak Thanks sooo much.
That is something that should definitively go in the doc http://sonata-project.org/bundles/ecommerce/develop/doc/reference/architecture/api.html …

**Comment by utilisezlinux** [comment]
Ok, so now, that works with a demo product, but can't get a product created by me on a created «book» prototype. I can have my product in the admin, but the json api outputs 
```
{"code":500,"message":"Could not find class MyBundle\\ProductBundle\\Entity\\Book inside XML element."}
```

What xml element?

**Comment by grosenbaum** [comment]
Thx @utilisezlinux for your help.
Don't hesitate to propose a PR to update the API documentation. :)

**Comment by grosenbaum** [comment]
@utilisezlinux thx for https://github.com/sonata-project/ecommerce/pull/321 :+1:

**Comment by utilisezlinux** [comment]
:)
