### ISSUE TITLE
Add product variations form in basket

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/ecommerce#253]
Useful for quick change product variation.
I have 80% now.
W8 for issue #258

**Comment by wbloszyk** [comment]
Done, work in:
http://serwer1398955.home.pl/sklep_domeny/web/app_dev.php/shop/basket/

I will create Pull Request after change products variation list to product form in modal.

**Comment by jordisala1991** [comment]
Please open a new issue with a complete report of the problem.
