### ISSUE TITLE
ProductMenuBuilder - same category name issue.

### ISSUE THREAD

**Issue by danvbe** [sonata-project/ecommerce#268]
This is related to generating the Category menu in the catalog part.

Currently, when a menu has children, they are created using `getCategoryTitle($category)` function of the [ProductMenuBuilder class](https://github.com/sonata-project/ecommerce/blob/master/src/ProductBundle/Menu/ProductMenuBuilder.php#L176). This function is generating a menu name based on the category Title.
But this will not work well if someone is having categories with same name and same number of products in it (in my case... I had 2 subcategories with same name, with different parent categories). This is because KnpMenu finds an already existent menu element with that name and it is not generating a new menu entry but overwriting the already existent one.
This is easily fixable by creating the child menus using the categoryId as name and after that setting a label for the newly created child menu (using the `getCategoryTitle($category)` function mentioned above). We only need that fancy HTML to be displayed, not to actually be used as menu identifier (menu name).

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
