### ISSUE TITLE
How to add my forked ecommerce repo to composer?

### ISSUE THREAD

**Issue by piotr-galas** [sonata-project/ecommerce#274]
Hi,

I would like to check my fix so I cloned ecommerce repo added fix and want to update my composer.json to use it.

```
    "repositories":
        [
            {
                "type": "git",
                "url": "https://github.com/piotr-galas/ecommerce"
            }
        ],
    "require": {
        // what I had before =>        "sonata-project/ecommerce": "~2.3@dev"
        "ecommerce": "dev-master"
    }
```

How should I set up composer.json?

I did it like above but I get

```
$> composer.phar update -o
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/local/bin/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Updating dependencies (including require-dev)              
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ecommerce could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by bosnianmostar** [comment]
Hello guys,

I am having issue with ecommerce, I tried to add :
"require" {
...
"sonata-project/ecommerce": "2.3@dev",
...
}
but after that I got an error, and after little bit of research I found that min-stab and pref.stab might help me, but I couldn't solve problem..

I tried and minimum-stability and prefer stable didnt help me.. here is picture of error and also of my composer.json

![error](https://cloud.githubusercontent.com/assets/17853339/13983225/aded715e-f0ee-11e5-98a2-46083c1dcccc.png)

**Comment by hacfi** [comment]
@bosnianmostar Instead of manually editing the composer.json try running:
```
composer require sonata-project/ecommerce
```

If that doesn’t help try
```
composer require sonata-project/ecommerce:"dev-master"
```

or

```
composer require sonata-project/ecommerce:"~2.3@dev"
```

**Comment by bosnianmostar** [comment]
I decided to switch to Sylius commerce, its seems much more funnier than sonata, but after some time on installation i received error 
"[RuntimeException]
Running git clone https://github.com/bergie/create.git failed with 1" I really dont know how to fix it
