### ISSUE TITLE
Clone issue

### ISSUE THREAD

**Issue by danvbe** [sonata-project/ecommerce#276]
I am using Sonata eCommerce in a project I am working on.
I was trying to add new fields to the basket entity, but for some reason they were not persisted across session. So I was trying to solve this by setting the Basket to work as entity (saving basket to Database, not in session). This way I found out that in the deliveryAction and paymentAction (for some reason I cannot really explain) we have the basket cloned right from beginning. This made the EntityManager trying to save a new basket record and raised a unique constraint error every time I was trying to process the basket on one of the steps mentioned above (there may be ONLY one basket per customer). 

I solved it by removing the "clone" code from [here](https://github.com/sonata-project/ecommerce/blob/master/src/BasketBundle/Controller/BasketController.php#L261) and [here](https://github.com/sonata-project/ecommerce/blob/master/src/BasketBundle/Controller/BasketController.php#L210).

**Comment by jeroendk** [comment]
I think this one can be closed, seems to fixed a long time ago?
