### ISSUE TITLE
unable to create product with sonatat:product:generate

### ISSUE THREAD

**Issue by bertinl0609** [sonata-project/ecommerce#280]
Hi,

i wanted to create a product with the command line but i receive the following message.

  [Exception]
  Please initialize a ProductBundle first in the Application directory

After having a look at the command line i see it checks for a Application/Sonata/ProductBundle in 
%s/../src/Application/Sonata/ProductBundle (line 54 of GenerateProductCommand.php) while mine is as all others of SonataBundles in App/Application. Why not use the line from the config file where you can mention the class for the product and parse it to check if the folder/file exists ?
sonata_product:
    class:
        product:              Application\Sonata\ProductBundle\Entity\Product

Exception trace:
 () at D:\xampp\htdocs\dev2\keusters\vendor\sonata-project\ecommerce\src\ProductBundle\Command\GenerateProductCommand.php:58
 Sonata\ProductBundle\Command\GenerateProductCommand->execute() at D:\xampp\htdocs\dev2\keusters\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:244
 Symfony\Component\Console\Command\Command->run() at D:\xampp\htdocs\dev2\keusters\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:900
 Symfony\Component\Console\Application->doRunCommand() at D:\xampp\htdocs\dev2\keusters\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:191
 Symfony\Component\Console\Application->doRun() at D:\xampp\htdocs\dev2\keusters\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\xampp\htdocs\dev2\keusters\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:121
 Symfony\Component\Console\Application->run() at D:\xampp\htdocs\dev2\keusters\app\console:27

sonata:product:generate product service_id

**Comment by jordisala1991** [comment]
Related to #332 Closing this one as duplicate
