### ISSUE TITLE
Using Symfony UserInterface instead of FOSUserBundle UserInterface?

### ISSUE THREAD

**Issue by eko** [sonata-project/ecommerce#284]
Hi,

A customer is actually linked to a FOSUserBundle user (`FOS\UserBundle\Model\UserInterface`) as specified in the CustomerInterface (https://github.com/sonata-project/ecommerce/blob/master/src/Component/Customer/CustomerInterface.php).

As `CustomerInterface` is also used in a lot of classes, projects that does not use FOSUserBundle (such eZPublish for instance) have to redefine a lot of things just to bypass this issue.

What about using the `Symfony\Component\Security\Core\User\UserInterface` instead to do not limit Sonata ecommerce using FOSUserBundle by default?

**Comment by mathewrapid** [comment]
+1

**Comment by jordisala1991** [comment]
Already done, closing
