### ISSUE TITLE
Creation of product  "validateOneMainCategory()"

### ISSUE THREAD

**Issue by Mays** [sonata-project/ecommerce#293]
Hello,

When i   add a  product in sonata admin i get this

Catchable Fatal Error: Argument 1 passed to Sonata\ProductBundle\Entity\BaseProduct::validateOneMainCategory() must be an instance of Symfony\Component\Validator\ExecutionContext, instance of Symfony\Component\Validator\Context\LegacyExecutionContext given in /media/mehdi/Data1/work/phpwork/cookbook/vendor/sonata-project/ecommerce/src/ProductBundle/Entity/BaseProduct.php line 949

**Comment by grosenbaum** [comment]
ping @rande

**Comment by grosenbaum** [comment]
It's corrected now. Could you check and close this issue ?

**Comment by cbastienbaron** [comment]
indeed :+1:

**Comment by cbastienbaron** [comment]
already merge : https://github.com/sonata-project/ecommerce/pull/314

branch dev-develop

**Comment by jordisala1991** [comment]
Closing as it is already fixed
