### ISSUE TITLE
Declaration of Sonata\ProductBundle\Entity\BaseProduct::validateOneMainCategory() 

### ISSUE THREAD

**Issue by yellowbig** [sonata-project/ecommerce#312]
Hello
When i run "php app/console" in the sonata-sandbox,i get this error 

PHP Fatal error:  Declaration of Sonata\ProductBundle\Entity\BaseProduct::validateOneMainCategory() must be compatible with Sonata\Component\Product\ProductInterface::validateOneMainCategory(Symfony\Component\Validator\ExecutionContext $context) in /home/shuo/workspace/localserver/sonata/vendor/sonata-project/ecommerce/src/ProductBundle/Entity/BaseProduct.php on line 28

**Comment by grosenbaum** [comment]
Seems to be linked with #293

**Comment by grosenbaum** [comment]
It's corrected now. Could you check and close this issue ?

**Comment by grosenbaum** [comment]
Thx @yellowbig
