### ISSUE TITLE
Unable to list products by collections

### ISSUE THREAD

**Issue by numerogeek** [sonata-project/ecommerce#322]
Hey,

I saw in the product bundle there's a controller to handle product by collections.
So I've added a route : 
sonata_product_catalog_collection:
    path:     /hello/{name}/{collectionId}
    defaults: { _controller: SonataProductBundle:Collection:listProducts }

But it doesnt work. seems that the controller call an method that does not exist (anymore/yet) ? 

Fatal error: Call to undefined method Sonata\ProductBundle\Entity\ProductSetManager::getProductsByCollectionIdPager() in \vendor\sonata-project\ecommerce\src\ProductBundle\Controller\CollectionController.php on line 85

**Comment by jeroendk** [comment]
What is the purpose of the "sonata.product.set.manager"? There are no implemented methods in it. It looks like the method `getProductsByCollectionIdPager` never existed and all other calls to this manager are handled by the ProductManager.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.

**Comment by jeroendk** [comment]
@core23 I did and it still exists. Will create a pull request but I am not sure if the missing method needs to be created or the calling controller action can be dropped? 

Also, the class `Sonata\ProductBundle\EntityProductSetManager` does nothing so if anyone can recall the purpose of this class, that would be helpful.

**Comment by core23** [comment]
Can you please fill out a new issue using the issue template @jeroendk 
This will help to examine the problem.
