### ISSUE TITLE
error validateBlock()

### ISSUE THREAD

**Issue by lumilo8** [sonata-project/ecommerce#328]
Hi!! 
This commit https://github.com/sonata-project/ecommerce/commit/2dd58d5694d2a2587e980b9b1be686f00a7a2b86 generates me a error with validateBlock:

PHP Fatal error:  Declaration of Sonata\OrderBundle\Block\RecentOrdersBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /var/www/casa-verde-fresh/vendor/sonata-project/ecommerce/src/OrderBundle/Block/RecentOrdersBlockService.php on line 140

Thanks!

**Comment by rande** [comment]
@lumilo8 if you cannot mix stable and unstable dependencies, so you need to use dev version of all Sonata's bundles to be in sync with upcoming changes.

**Comment by lumilo8** [comment]
Thanks @rande you're right, i have all stable versions on sonata bundles, but sonata ecommerce hasn't stable. Anyway, i solved the error. Thanks for all!

**Comment by lumilo8** [comment]
Hi, again.
I'm trying to install a stable version of SonataEcommerce with this:
"sonata-project/ecommerce": "dev-develop#2dd58d5694d2a2587e980b9b1be686f00a7a2b86"

because the rest of sonata bundles are on stable versions... it doesn't work, requires seo-bundle 2.0.
I don't know how do it...could you help me?

Thanks!

**Comment by jordisala1991** [comment]
The dependency hell problem was already solved with the new branch system
