### ISSUE TITLE
knplabs/knp-menu-bundle 2.0

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/ecommerce#348]
is it possible to support knplabs/knp-menu-bundle 2.0 version?

Thanks

**Comment by Soullivaneuh** [comment]
@josephzhao Feel free to make a PR. :+1:

**Comment by Soullivaneuh** [comment]
BTW, this is already supported on develop branch: https://github.com/sonata-project/ecommerce/blob/develop/composer.json#L38

@rande When this will be on master?

**Comment by josephzhao** [comment]
how can I use develop branch in my composer.json file,  "sonata-project/ecommerce": "2.3.x-dev", is not working

**Comment by hacfi** [comment]
@josephzhao Try `dev-develop`

**Comment by josephzhao** [comment]
when i click sonataadmin dashboard product, there is the error:

An exception occurred while executing 'SELECT count(DISTINCT p0_.id) AS sclr0 FROM product__product p0_ LEFT JOIN product__product_category p1_ ON p0_.id = p1_.product_id LEFT JOIN classification__category c2_ ON p1_.category_id = c2_.id LEFT JOIN product__product_collection p3_ ON p0_.id = p3_.product_id LEFT JOIN classification__collection c4_ ON p3_.collection_id = c4_.id WHERE p0_.product_type IN ()':

SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near ")"
LINE 1: ..._ ON p3_.collection_id = c4_.id WHERE p0_.product_type IN ()

**Comment by Soullivaneuh** [comment]
@josephzhao Please open another issue for this if no related issue already exists.

I close this one as resolved.
