### ISSUE TITLE
product list error for dev_develop version

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/ecommerce#349]
when i click sonataadmin dashboard product, there is the error:
(the table product__product is empty)

An exception occurred while executing 'SELECT count(DISTINCT p0_.id) AS sclr0 FROM product__product p0_ LEFT JOIN product__product_category p1_ ON p0_.id = p1_.product_id LEFT JOIN classification__category c2_ ON p1_.category_id = c2_.id LEFT JOIN product__product_collection p3_ ON p0_.id = p3_.product_id LEFT JOIN classification__collection c4_ ON p3_.collection_id = c4_.id WHERE p0_.product_type IN ()':

SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near ")"
LINE 1: ..._ ON p3_.collection_id = c4_.id WHERE p0_.product_type IN ()

**Comment by npotier** [comment]
:+1:

**Comment by utkarsh2k2** [comment]
I am getting the same error. Also when I click on "add new" product I get a blank page . Somebody please look into the issue.

**Comment by finchen** [comment]
it seems you have to add a product type first
https://sonata-project.org/bundles/ecommerce/develop/doc/reference/bundles/product.html

**Comment by jordisala1991** [comment]
As @finchen says, you must have a product type. Closing because it should be solved. If the error is still there, and this issue is relevant, ping me to reopen
