### ISSUE TITLE
How to start to use the API?

### ISSUE THREAD

**Issue by Avtonom** [sonata-project/ecommerce#353]
Unable to create Basket. What are the parameters you need to pass? I give the currency as a string. Error response.

`sonata-project/ecommerce: "dev-develop"` - other versions are hopelessly obsolete.

**Comment by Avtonom** [comment]
@rande @Soullivaneuh  Tell me please. I am ready to develop API

**Comment by OskarStark** [comment]
Can you please post more information, code samples, which call are you doing and a stack trace?

Thank you

**Comment by Avtonom** [comment]
POST /ecommerce/baskets.json HTTP/1.1
----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="currency"

RUR
----WebKitFormBoundaryE19zNvXGzXaLvS5C



Request:
{
    "code": 400,
    "message": "Validation Failed",
    "errors": {
        "errors": [
            "The value must not be null.",
            "The value must not be null.",
            "The value must not be null."
        ],
        "children": {
            "options": [],
            "currency": []
        }
    }
}

**Comment by rande** [comment]
Please note, the API is a work in progress. So it can be very unstable. Did you check behat test on the sandbox ?

**Comment by Avtonom** [comment]
> the API is a work in progress. So it can be very unstable.
I understand, ready to edit

> Did you check behat test on the sandbox ?
through the sandbox and REST emulator

**Comment by Avtonom** [comment]
=)

**Comment by Avtonom** [comment]
@rande @Soullivaneuh @OskarStark Tell me please.

**Comment by Avtonom** [comment]
https://github.com/sonata-project/ecommerce/blob/develop/src/BasketBundle/Resources/config/serializer/Entity.BaseBasket.xml#L11
virtual-property name="options"
property         name="currency"

group validation = api use https://github.com/sonata-project/ecommerce/blob/develop/src/BasketBundle/Form/ApiBasketType.php#L66
https://github.com/sonata-project/ecommerce/blob/develop/src/BasketBundle/Resources/config/validation.xml#L79
But I see that in validation for the group "api" used the following fields: currency, locale, deliveryMethodCode, paymentMethodCode

I'm looking for the problem in the wrong places or not these fields were derived in the documentation?

**Comment by linkwair** [comment]
I use the latest stable release (2.1.1) and I have the same error of Avtonom when I want post a basket. A solution was found ?

**Comment by Avtonom** [comment]
@linkwair not

**Comment by jordisala1991** [comment]
Closing in favor of #453 

If those are different issues, please ping me to reopen. I dont want duplicate issues.
