### ISSUE TITLE
How to Install it for Symfony3?

### ISSUE THREAD

**Issue by napestershine** [sonata-project/ecommerce#358]
Hi 

I am trying to install it for my new project which is in symfony3. Can anyone help with installation process as it fails everytime.

Thanks

**Comment by deantomasevic** [comment]
I need help too.

**Comment by kadinho** [comment]
Help

**Comment by Soullivaneuh** [comment]
Those packages are WIP for refactoring.

Please see:

* https://github.com/sonata-project/dev-kit/issues/140
* https://github.com/sonata-project/dev-kit/issues/138

**Comment by Soullivaneuh** [comment]
Ecommerce is not compatible with Symfony 3 yet because of user-bundle dependency.

Adding it on composer was a mistake.

**Comment by sopopo** [comment]
Hi
What about a compatible version with symfony 3 now ??
Tanks for your answer

**Comment by WebToolsde** [comment]
seems not to be compatible with symfony 4, too. I tried to install. No Chance, I think.
