### ISSUE TITLE
problem with Ogone payment method and ChoiceList with Symfony 2.8.3 installed

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/ecommerce#360]
Notice: Object of class Sonata\Component\Payment\Ogone\OgonePayment could not be converted to int
Stack Trace
    in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/ChoiceList/ChoiceList.php at line 471  -
             */
            protected function fixIndex($index)
            {
                if (is_bool($index) || (string) (int) $index === (string) $index) {
                    return (int) $index;
                }
    at ErrorHandler ->handleError ('8', 'Object of class Sonata\Component\Payment\Ogone\OgonePayment could not be converted to int', '/Users/Stephane/Sites/Falciform/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/ChoiceList/ChoiceList.php', '471', array('index' => object(OgonePayment)))
    in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/ChoiceList/ChoiceList.php at line 471

**Comment by stphnpt** [comment]
Notice: Object of class Sonata\Component\Payment\PassPayment could not be converted to int
Same issue with Pass Payment method and Symfony 2.8.4-DEV installed

**Comment by jordisala1991** [comment]
This issue is too old an probably solved already, please ping me if not and I will reopen.
