### ISSUE TITLE
SonataProject -eCommerce

### ISSUE THREAD

**Issue by Billybroksen** [sonata-project/ecommerce#361]
Hello guys,

I am having issue with ecommerce, I tried to add :
"require" {
    ...
    "sonata-project/ecommerce": "2.3@dev",
    ...
}
but after that I got an error, and after little bit of research I found that min-stab and pref.stab might help me, but I couldn't solve problem..

 I tried and minimum-stability and prefer stable didnt help me.. here is picture of error and also of my composer.json

![error](https://cloud.githubusercontent.com/assets/17853339/13979181/e474cc6c-f0d6-11e5-9b56-29c42cba277c.png)

**Comment by deantomasevic** [comment]
Same error..

**Comment by Soullivaneuh** [comment]
@Billybroksen Please next time:

* Follow issue template. This is needed for save us time.
* Please do not use screenshot but copy/paste under code blocks.

As you certainly know, `ecommerce` was not stable at all. Not stable means BC break at any moment.

For this case, branches was refactored and a tags was added to keep old work (0.0.1 and 1.0.0).

But this will be not maintained anymore.

More information here: https://github.com/sonata-project/dev-kit/issues/138#issuecomment-228302524

Also, a quick view on Packagist already give you a hint of what is changed: https://packagist.org/packages/sonata-project/ecommerce

Regards.
