### ISSUE TITLE
Create stable release

### ISSUE THREAD

**Issue by core23** [sonata-project/ecommerce#365]
There is no stable release yet

**Comment by Soullivaneuh** [comment]
What is the status of this project?

Would be great to integrate on dev-kit before.

**Comment by stphnpt** [comment]
Is it possible to open a 3.x-dev branch with dependencies on associated Sonata Bundles ?

**Comment by Soullivaneuh** [comment]
> Is it possible to open a 3.x-dev branch with dependencies on associated Sonata Bundles ?

Not for now but this is still WIP.

**Comment by stphnpt** [comment]
Yes, in the meantime, it would be nice to have ecommerce master (or develop ?) updated with dependencies on current 3.x bundles
