### ISSUE TITLE
update composer error with Sonata\CustomerBundle

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/ecommerce#437]
Hello All
I have this error when i update the composer

[Doctrine\Common\Annotations\AnnotationException]                          
    [Creation Error] The annotation @QueryParam declared on method Sonata\Cus  
  tomerBundle\Controller\Api\AddressController::getAddressesAction() does not  
   have a property named "array". Available properties: requirements, map, al  
  lowBlank, name, key, default, description, strict, nullable, incompatibles   
                                                                               
                 Thanks

Joseph

**Comment by greg0ire** [comment]
Could you (or anyone) please contribute something similar to [this](https://github.com/sonata-project/SonataUserBundle/pull/805) ?

**Comment by josephzhao** [comment]
[Doctrine\Common\Annotations\AnnotationException]                                                                                                                                         
  [Creation Error] The annotation @QueryParam declared on method Sonata\CustomerBundle\Controller\Api\CustomerController::getCustomersAction() does not have a property named "array". Available properties: requirements, map, allowBlank, name, key, default, description, strict, nullable, incompatibles

**Comment by greg0ire** [comment]
What?

**Comment by josephzhao** [comment]
I found solution, change the   "friendsofsymfony/rest-bundle" version to 1.7,  latest version doesn't support array

**Comment by jordisala1991** [comment]
It depends on the version. >2 use array, <2 use map. this needs a PR similar to what @greg0ire posted.
