### ISSUE TITLE
is MopaBootstrap Required?

### ISSUE THREAD

**Issue by Filoz** [sonata-project/ecommerce#442]
In https://github.com/sonata-project/ecommerce/blob/7e778d57d1229df3f73b453404f9e7360b0ca923/src/BasketBundle/Resources/views/Form/label.html.twig#L1 and https://github.com/sonata-project/ecommerce/blob/7e778d57d1229df3f73b453404f9e7360b0ca923/src/CustomerBundle/Resources/views/Form/label.html.twig#L1

the twig file extends MopaBootstrapBundle that is not a required package.
and without MopaBoostrapBundle this is the result

`Unable to find template "MopaBootstrapBundle:Form:fields.html.twig" `

**Comment by Filoz** [comment]
Is really necessary this https://github.com/sonata-project/ecommerce/blob/7e778d57d1229df3f73b453404f9e7360b0ca923/src/BasketBundle/Resources/views/Basket/delivery_address_step.html.twig#L20 ?

this is the linked themplate: https://github.com/sonata-project/ecommerce/blob/7e778d57d1229df3f73b453404f9e7360b0ca923/src/BasketBundle/Resources/views/Form/label.html.twig

Removing the `{% form_theme form 'SonataBasketBundle:Form:label.html.twig' %}` and the `label.html.twig `file should work.

Can I send a pull request for this?

**Comment by OskarStark** [comment]
> Can I send a pull request for this?

Please, we will review it shortly

**Comment by Filoz** [comment]
sent :) #443
