### ISSUE TITLE
OmniPay Integration

### ISSUE THREAD

**Issue by Filoz** [sonata-project/ecommerce#448]
This is not an issue, but I would like to ask if do you think that an integration for https://github.com/thephpleague/omnipay can be useful.
Using that lib simplify the step necessary to add different payment gateway... 

 For the integration we can take a look to https://github.com/Sylius/SyliusOmnipayBundle (I know, it refers to Omnipay v.1 but it's a start).

What do you think?

**Comment by Filoz** [comment]
Another bundle useful for the integration is https://github.com/colinodell/omnipay-bundle

**Comment by Filoz** [comment]
Otherwise Payum che be a very good choice , it also has a Symfony Bubdle https://github.com/Payum/PayumBundle

**Comment by Filoz** [comment]
Another option would be http://jmspaymentcorebundle.readthedocs.io/en/stable/guides/accepting_payments.html

I will check them in next days... every opinion / suggestion are welcome

**Comment by pixel-paul** [comment]
I have started a project using omnipay (worldpay specifically) and am integrating it with the e-commerce bundle, so this would get my vote. I actually used this https://github.com/thephpleague/omnipay-worldpay

**Comment by Filoz** [comment]
hi @pixel-paul , did you start writing something to integrate sonata with omnipay or you haven't started yet?

**Comment by makasim** [comment]
Payum provides a lot of useful features for projects like commerce framework. 

1. Well though extensions and customization points.
2. Store credentials in a database.
3. Encrypt credentials.
4. Great bundle for Symfony. Profiler, debugger, controllers and so on.
5. Supports gateways which require js (like Stripe.JS) or custom snippet like Klarna Checkout.
6. Sylius uses it for a long time. 

It provides a bridge to Omnipay library so you can use those gateways in Payum (same for JMSPayment btw).

Disclaimer: I am the author of Payum.

**Comment by greg0ire** [comment]
Maybe we should just write a bunch of interfaces in sonata-project/ecommerce and implement them with adapters, so that people can pick their favorite payment solution?

**Comment by pixel-paul** [comment]
@Filoz I have got a working version with OmniPay. What I ended up doing was extending the BasePayment class and injected OmniPay into the sendBank() method and then managed the call back with the sonata e-commerce methods. Not the most glamorous solution, but one that worked given WorldPay's payment gateway nuances (it is a little frustrating). What I had wanted to do was remove OmniPay altogether, however I haven't got around to that bit yet.

**Comment by Filoz** [comment]
@makasim yes, you library is really interesting!
have you some example about how did you, or other team, integrate your library?

@greg0ire ... I aggree, this kind of feature will help everyone to add a new payment solution

@pixel-paul , can you upload your code somewhere? maybe in a fork of sonata-ecommerce.
the only problem I find so far is that omnipay [doesn't support Symfony >=3](https://github.com/thephpleague/omnipay/blob/2.3/README.md) but... in the future they will release Omnipay v3 that supports Symfony 3

**Comment by makasim** [comment]
Sylius is the one publicly available integration. The code could be found here: https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/PayumBundle

**Comment by nicolasricci** [comment]
Hi all,
Has there been any progress made on this since May? I believe using an existing payment gateway bundle is the way forward.
I have already worked with OmniPay and Payum so happy to help either way. 
@pixel-paul have you made any progress on your side?

**Comment by pixel-paul** [comment]
@nicolasricci - completely stalled but will be revisiting this over the next couple of weeks with another developer.

**Comment by nicolasricci** [comment]
@pixel-paul ok thanks for the update. I am having a go with Payum this afternoon, will keep you updated.

**Comment by makasim** [comment]
@nicolasricci don't hesitate to ask any questions regarding Payum

**Comment by nicolasricci** [comment]
Quick update, I have managed to link Payum to Sonata e-commerce. My current configuration still requires creating a separate service for each payment gateway but the capture/callback actions are then handled by Payum. 
Not sure it is the way forward especially since transactions are currently kept in 2 separate tables (Sonata payment_transaction and Payum payment)
Any thought?

**Comment by nicolasricci** [comment]
Update n°2: I have finally managed to create a `PayumPayment` class that can be used by any gateway then (only tested with Stripe and Stripe JS so far)
Only configuration required is to declare a service for each payment (and update payum and sonata config files accordingly)

```
services:
    app.payment.stripe:
        class: Application\Sonata\PaymentBundle\Gateways\PayumPayment
        arguments: ['@payum','@router', '@logger', '@sonata.payment.transformer.basket', {code: 'stripe', name: 'Stripe'}]
        tags:
            - { name: sonata.payment.method }

    app.payment.stripe_js:
        class: Application\Sonata\PaymentBundle\Gateways\PayumPayment
        arguments: ['@payum','@router', '@logger', '@sonata.payment.transformer.basket', {code: 'stripe_js', name: 'Stripe JS'}]
        tags:
            - { name: sonata.payment.method }
```

I am waiting for your feedbacks to see if this is worth packaging it in a PR

**Comment by Filoz** [comment]
@nicolasricci imho this can be a really "simply" and good solution!

**Comment by makasim** [comment]
> Not sure it is the way forward especially since transactions are currently kept in 2 separate tables (Sonata payment_transaction and Payum payment)

Payum does not require that. Sylius for example stores everything in its own model Payment. To make it work you need an action that takes payum data (usually an array) and does the sub request with it: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php#L20

**Comment by nicolasricci** [comment]
@makasim yeah I figured that out later on. It should not be too difficult to update the storage system to use Sonata Transaction model.

**Comment by Filoz** [comment]
@nicolasricci do you have any news about this feature?
if you put your code in a fork I will give a look for sure :)

**Comment by nicolasricci** [comment]
@Filoz sorry for the rather long silence but the project I was making these changes for has been on hold for a long time. I am happy to share the few services I have done to integrate Payum to Sonata payment system if you are still interested.

**Comment by Filoz** [comment]
@nicolasricci thank you for your reply!
Yes, it would be really useful!

**Comment by Nehadigi** [comment]
I am going to integrate my custom payment gateway and follow the guide lines but when I try to use my custom payment gateway. "Call to a member function transformIntoOrder() on boolean" error occurred. Even only class name changed remaining code is sonata predefined payment gateway but when I click on the payment button it shows the error.

**sonata_payment.yml**
sonata_payment:
    selector:             sonata.payment.selector.simple
    generator:            sonata.payment.generator.mysql
    transformers:
        order:                sonata.payment.transformer.order      # The service to transform an order into a basket
        basket:               sonata.payment.transformer.basket     # The service to transform a basket into an order
    services:
        pass:
            name:    Pass
            code:    pass
            browser: sonata.payment.browser.curl

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                shop_secret_key: assdsds
                url_callback:    sonata_payment_callback
                url_return_ko:   sonata_payment_error
                url_return_ok:   sonata_payment_confirmation
    class:
        order:                Application\Sonata\OrderBundle\Entity\Order
        transaction:          Application\Sonata\PaymentBundle\Entity\Transaction

    # Here you will enable the payment methods you wish to provide
    # and add your custom ones
    methods:
        pass: ~     # This is a provided method, we don't need to specify its service id
        mercadopago: app.payment.mercadopago    # Custom payment method, we specify the service id

**services.yml**
app.payment.Mercadopago:
        class: AppBundle\Payment\MercadopagoPayment
        arguments: ['@router', '@sonata.payment.transformer.basket']
        tags:
            - { name: sonata.payment.method}

**Comment by Filoz** [comment]
Hi @nicolasricci , I'm sorry to bother you:
do you have any update?

**Comment by jeroendk** [comment]
@nicolasricci Would be very interested in your integration! Are you able to share your work ?

**Comment by jeroendk** [comment]
Hi @makasim trying to integrate Payum in Sonata Ecommerce myself. How should I handle the notification callback from the payment provider. Should I somehow forward it to sonata and if so how would i accoumplish this ?

**Comment by nicolasricci** [comment]
@Filoz @jeroendk sorry guys I didn't receive any notification from Github and only checking this thread again now.
Here is the way I have set up things. Any question let me know

# sonata_payment.yml

```
sonata_payment:
    methods:
        stripe_js: app.payment.stripe_js
```

# payum.yml

```
payum:
    security:
        token_storage:
            AppBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        AppBundle\Entity\Payment: { doctrine: orm }

    gateways:
        stripe_js:
            factory: stripe_js
            publishable_key: %stripe_public_key%
            secret_key: %stripe_private_key%
```
# services.yml

```
services:
    app.payment.stripe_js:
        class: Application\Sonata\PaymentBundle\Gateways\PayumPayment
        arguments: ['@payum','@router', '@logger', '@request_stack', '@sonata.payment.transformer.basket', '@sonata.payment.transformer.order', {code: 'stripe_js', name: 'Credit/Debit Card (Stripe)'}]
        tags:
            - { name: sonata.payment.method }
    app.payum.listener:
        class: Application\Sonata\PaymentBundle\Listener\PayumListener
        arguments: ['@payum', '@payum.security.token_storage', '@sonata.basket', '@sonata.basket.factory', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: sonata.ecommerce.payment.post_callback, method: onPostCallback }
            - { name: kernel.event_listener, event: sonata.ecommerce.payment.post_callback, method: onPreCallback }
```

# PayumPayment class

```
<?php
namespace Application\Sonata\PaymentBundle\Gateways;

use Payum\Core\Payum;
use Payum\Core\Request\GetHumanStatus;
use Sonata\Component\Payment\BasePayment;
use Psr\Log\LoggerInterface;
use Sonata\Component\Basket\BasketInterface;
use Sonata\Component\Order\OrderInterface;
use Sonata\Component\Payment\TransactionInterface;
use Sonata\Component\Product\ProductInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Sonata\Component\Transformer\BasketTransformer;
use Sonata\Component\Transformer\OrderTransformer;

class PayumPayment extends BasePayment
{

    /**
     * @var RouterInterface
     */
    protected $router;

    /** @var  Payum */
    protected $payum;

    /** @var  array */
    protected $parameters;

    /** @var  RequestStack */
    protected $requestStack;

    /**
     * @param Payum $payum
     * @param RouterInterface $router
     * @param LoggerInterface $logger
     * @param RequestStack $requestStack
     * @param array $parameters
     */
    public function __construct(Payum $payum, RouterInterface $router, LoggerInterface $logger, RequestStack $requestStack, BasketTransformer $basketTransformer, OrderTransformer $orderTransformer, array $parameters)
    {
        $this->router = $router;
        $this->parameters = $parameters;
        $this->payum = $payum;
        $this->requestStack = $requestStack;
        $this->setLogger($logger);
        $this->addTransformer('basket', $basketTransformer);
        $this->addTransformer('order', $orderTransformer);
    }

    /**
     * {@inheritdoc}
     */
    public function isAddableProduct(BasketInterface $basket, ProductInterface $product)
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isBasketValid(BasketInterface $basket)
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isRequestValid(TransactionInterface $transaction)
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function handleError(TransactionInterface $transaction)
    {
        if ($transaction->getOrder()->isOpen()) {
            $transaction->getOrder()->setPaymentStatus($transaction->getStatusCode());
        }

        $this->report($transaction);

        return new Response('ko', 200, array(
            'Content-Type' => 'text/plain',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function sendConfirmationReceipt(TransactionInterface $transaction)
    {

        $request = $this->requestStack->getCurrentRequest();
        $token = $this->payum->getHttpRequestVerifier()->verify($request);
        $gateway = $this->payum->getGateway($token->getGatewayName());

        $gateway->execute($status = new GetHumanStatus($token));
        $payment = $status->getFirstModel();
        $details = $payment->getDetails();

        $transaction->setParameters(array_merge($transaction->getParameters(), $details));

        if (isset($details['error'])) {

            $transaction->setState(TransactionInterface::STATE_KO);
            $transaction->setStatusCode(TransactionInterface::STATUS_ERROR_VALIDATION);

            $transaction->getOrder()->setValidatedAt(new \DateTime());
            $transaction->getOrder()->setStatus(OrderInterface::STATUS_ERROR);
            $transaction->getOrder()->setPaymentStatus(TransactionInterface::STATUS_WRONG_CALLBACK);

            return new RedirectResponse(
                $this->router->generate('sonata_payment_error', $transaction->getParameters())
            );
        }

        $transaction->setState(TransactionInterface::STATE_OK);
        $transaction->setStatusCode(TransactionInterface::STATUS_VALIDATED);

        $transaction->getOrder()->setValidatedAt(new \DateTime());
        $transaction->getOrder()->setStatus(OrderInterface::STATUS_VALIDATED);
        $transaction->getOrder()->setPaymentStatus(TransactionInterface::STATUS_VALIDATED);

        return new RedirectResponse(
            $this->router->generate('sonata_payment_confirmation', $transaction->getParameters())
        );
    }

    /**
     * {@inheritdoc}
     */
    public function isCallbackValid(TransactionInterface $transaction)
    {
        if (!$transaction->getOrder()) {
            return false;
        }

        if ($transaction->get('check') == $this->generateUrlCheck($transaction->getOrder())) {
            return true;
        }

        $transaction->setState(TransactionInterface::STATE_KO);
        $transaction->setStatusCode(TransactionInterface::STATUS_WRONG_CALLBACK);
        $transaction->addInformation('The callback is not valid');

        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function sendbank(OrderInterface $order)
    {
        $gatewayName = $this->parameters['code'];

        $storage = $this->payum->getStorage('AppBundle\Entity\Payment');

        $payment = $storage->create();
        $payment->setNumber('ref');
        $payment->setCurrencyCode('EUR');
        $payment->setTotalAmount(123);
        $payment->setClientId('client id');
        $payment->setDescription('your description');
        $payment->setClientEmail('johndoe@example.com');
        $payment->setDetails(['metadata' => ['param' => 'value']]);

        $storage->update($payment);

        $captureToken = $this->payum->getTokenFactory()->createCaptureToken(
            $gatewayName,
            $payment,
            'sonata_payment_callback', // the route to redirect after capture
            ['bank' => $gatewayName, 'reference' => $order->getReference(), 'check' => $this->generateUrlCheck($order)]
        );

        return new RedirectResponse($captureToken->getTargetUrl());
    }

    /**
     * {@inheritdoc}
     */
    public function getOrderReference(TransactionInterface $transaction)
    {
        return $transaction->get('reference');
    }

    /**
     * @param TransactionInterface $transaction
     */
    public function applyTransactionId(TransactionInterface $transaction)
    {
        $transaction->setTransactionId($transaction->getOrder()->getReference());
    }

    public function addTransformer($id, $transformer)
    {
        parent::addTransformer($id, $transformer);
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->parameters['name'];
    }

    /**
     * {@inheritdoc}
     */
    public function getCode()
    {
        return $this->parameters['code'];
    }
}
```
# PayumListener class

```
<?php

namespace Application\Sonata\PaymentBundle\Listener;

use Application\Sonata\OrderBundle\Entity\OrderElement;
use Doctrine\Common\Persistence\ObjectManager;
use Payum\Core\Exception\InvalidArgumentException;
use Payum\Core\Payum;
use Sonata\Component\Basket\BasketFactoryInterface;
use Sonata\Component\Basket\BasketInterface;
use Sonata\Component\Event\PaymentEvent;
use Payum\Core\Storage\StorageInterface;
use Sonata\Component\Order\OrderInterface;

class PayumListener
{

    /**
     * @var Payum
     */
    protected $payum;

    /**
     * @var StorageInterface
     */
    protected $storage;

    /**
     * @var BasketInterface
     */
    protected $basket;
    /**
     * @var BasketFactoryInterface
     */
    protected $basketFactory;

    /**
     * @var ObjectManager
     */
    protected $objectManager;

    /**
     * PayumListener constructor.
     * @param Payum $payum
     * @param StorageInterface $storage
     */
    public function __construct(Payum $payum, StorageInterface $storage, BasketInterface $basket, BasketFactoryInterface $basketFactory, ObjectManager $objectManager)
    {
        $this->payum = $payum;
        $this->storage = $storage;
        $this->basket = $basket;
        $this->basketFactory = $basketFactory;
        $this->objectManager = $objectManager;
    }

    /**
     * @param PaymentEvent $event
     */
    public function onPreCallback(PaymentEvent $event)
    {

        $transaction = $event->getTransaction();
        $order = $event->getOrder();

        // implement your own logic here
     

    }

    /**
     * @param PaymentEvent $event
     */
    public function onPostCallback(PaymentEvent $event)
    {

        $transaction = $event->getTransaction();
        $order = $event->getOrder();
        $parameters = $transaction->getParameters();

        if (false == $token = $this->storage->find($parameters['payum_token'])) {
            throw new InvalidArgumentException(sprintf('A token with hash `%s` could not be found.', $parameters['payum_token']));
        }

        $this->payum->getHttpRequestVerifier()->invalidate($token);


        if (OrderInterface::STATUS_VALIDATED === $order->getStatus()) {
             // implement your own logic here
        }

    }


}
```

**Comment by jeroendk** [comment]
@nicolasricci Thanks for sharing!

**Comment by Filoz** [comment]
@nicolasricci  thank you very much!
Surely I will try your code!
