### ISSUE TITLE
Basket is  is not emptied when payment process is completed

### ISSUE THREAD

**Issue by Filoz** [sonata-project/ecommerce#450]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2
sonata-project/block-bundle              3.3.2
sonata-project/cache                     1.0.7
sonata-project/classification-bundle     3.3.0
sonata-project/core-bundle               3.4.0
sonata-project/datagrid-bundle           2.2.1
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.4
sonata-project/easy-extends-bundle       2.2.0
sonata-project/exporter                  1.7.1
sonata-project/formatter-bundle          3.2.0
sonata-project/intl-bundle               2.x-dev 90e304f
sonata-project/media-bundle              3.5.1
sonata-project/notification-bundle       3.1.0
sonata-project/seo-bundle                2.x-dev 43c4437
sonata-project/user-bundle               dev-master 34a771f

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.1  Symfony SwiftmailerBundle
symfony/symfony            v3.2.8  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 17 2017 13:58:38) ( ZTS )
```

## Subject
After payment complete, the basket soul be emptied

## Steps to reproduce
Add a product to basket, complete checkout process
Go to basket, the product will be still here 
## Expected results
The basket has no products

**Comment by Filoz** [comment]
I found this commit https://github.com/sonata-project/ecommerce/pull/242
I will check to understand why it doesn't clear the basket anymore

**Comment by greg0ire** [comment]
> the basket soul be emptied
Let's call a Dementor then 😄 

>  I will check to understand why it doesn't clear the basket anymore

The commit message is not really helpful:
> Fixed basket reset in db

Good luck debugging that!

**Comment by Filoz** [comment]
Ahahah, it was a typo : "should be"

**Comment by greg0ire** [comment]
> Ahahah, it was a typo : "should be"
I know full well :trollface:

**Comment by ZRazor** [comment]
I debugged a little and found the problem. 
So what goes on when basket is stored in session:
1) You are creating an order, your basket is stored in session with name `sonata/basket/factory/customer/1` (you are an authed user with customer id = 1), everything is fine.
2) `PaymentController::sendbankAction` calls this function `$this->getBasketFactory()->reset($basket);`.
3) In `BasketSessionFactory` we have this code:
```php
    public function reset(BasketInterface $basket, $full = true)
    {
        $basket->reset($full);
        $this->save($basket);
    }
```
And in `BasketIntityFactory` we have:
```php
    public function reset(BasketInterface $basket, $full = true)
    {
        if ($full && $basket->getCustomerId()) {
            $this->basketManager->delete($basket);
        } else {
            $basket->reset($full);
            $this->save($basket);
        }
    }
```
So anyway it is reset and saved and `$full` is `true`.
4) `Basket::reset` does this:
```php
        if ($full) {
            //...
            $this->customerId = null;
            $this->customer = null;
            //...
        }
```
5) So after `$basket->reset($full)` you have a different basket without link to a customer.
6) It tries to save it, but this code in `BaseBasketFactory`
```php
    protected function storeInSession(BasketInterface $basket)
    {
        $this->session->set($this->getSessionVarName($basket->getCustomer()), $basket);
    }

    protected function getSessionVarName(CustomerInterface $customer = null)
    {
        if (null === $customer || null === $customer->getId()) {
            return self::SESSION_BASE_NAME.'new';
        }

        return self::SESSION_BASE_NAME.$customer->getId();
    }
```
 returns a different session name for a basket - `sonata/basket/factory/customer/new` and your original basket `sonata/basket/factory/customer/1` is still there and still full.

---
I guess we can just replace `$this-save($basket)` with `$this->clearSession($basket->getCustomer);`
@greg0ire what do you think?

**Comment by greg0ire** [comment]
Uuuh yeah probably. I don't know much about this package, you know? :sweat_smile:

**Comment by ZRazor** [comment]
@greg0ire Yea) already got the right solution - preparing PR now.
