### ISSUE TITLE
Payment Confirmation event shouldn't be dispatched multiple time

### ISSUE THREAD

**Issue by Filoz** [sonata-project/ecommerce#451]
## Subject
In https://github.com/sonata-project/ecommerce/blob/2.x/src/PaymentBundle/Controller/PaymentController.php#L56 it tries to call handleConfirmation to make the payment.

I'm trying with "pass" payment, so I don't know if it's a behavior that happens only with this kind of payment or happens with every payment options:
the page url after payment  is "payment/confirmation?bank=pass&reference=170526000004&check=8e03f6aecc2c00e27716abf7edc78054e0675665"; 
If I **reload** the page `$this->getPaymentHandler()->handleConfirmation` is called again, so PaymentEvents::CONFIRMATION is dispatched again.
I think that if an order is payed... nothing should happen if someone reload the page.
Maybe we should think about adding a condition in `confirmationAction ` to check if the payment was already done and if so... show the correct template without trying to make the payment again.

What do yo think?

## Steps to reproduce
Add something to the basket, proceed with every step, and when you arrive to the confirmation page try to reload the page
## Expected results
PaymentEvents::CONFIRMATION is dispatched only first time
## Actual results
PaymentEvents::CONFIRMATION every time page reload

**Comment by greg0ire** [comment]
> without trying to make the payment again

What?! You mean people can pay several times???

**Comment by Filoz** [comment]
I investigated better than before, and it looks that the event PaymentEvents::CONFIRMATION is dispatched every time the page reload... but the payments seems to be executed only the first time.
So, the only thing to do is to not dispatch the event every time the page load...

**Comment by greg0ire** [comment]
Probably... what listeners are bound to that event? You probably don't want confirmation emails to be sent twice indeed.

**Comment by Filoz** [comment]
I can't find any event listener for that event

**Comment by greg0ire** [comment]
Ok so it's aimed for external listeners. But I did not find documentation about that event, what it is meant for, etc.
