### ISSUE TITLE
update with composer

### ISSUE THREAD

**Issue by geniuspegasus** [sonata-project/ecommerce#455]
when i try to install sonata ecommerce with composer.phar update

error
[runtimeExeption]
Could not load package orange-opensource/orange-boosted-bootstrap in http://packagist.org: [unexpectedValueException] Could not parse version constraint v4.0.0-alpha.3.1 Invalid version string "v4.0.0-alpha.3.1" .
Can you help me please ?

**Comment by OskarStark** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
