### ISSUE TITLE
Product class in not detecting correctly while creating a new product

### ISSUE THREAD

**Issue by azlotnikov** [sonata-project/ecommerce#511]
## Subject

In #502 I removed `ProductAdmin::getClass` method to avoid recursion after sonata-admin-bundle update. There is no more recursion in product editing, but in product creating class is not detected correctly (my bad 🙃 ).
I want to fix this, but I need some help.
We need to detect product class manualy (using `provider` parameter from query) only in create action. Before this was done by `if ($this->hasSubject())` inside `getClass` method, but we cannot do this now, because it stucks in recursion (since `hasSubject` calls `getClass`). 
@greg0ire @jordisala1991 Do you have any ideas how to do it right? 
I thought about `if ($this->getRequest()->get('_route') == 'admin_sonata_product_product_create')` but it's obviously not a good idea.

**Comment by jordisala1991** [comment]
Maybe you can restore the old method but without the other condition?

```
    /**
     * @return string
     */
    public function getClass()
    {
        if ($class = $this->getProductClass()) {
            return $class;
        }

        return parent::getClass();
    }
```

Could that work?

**Comment by ZRazor** [comment]
@jordisala1991 not working, it tries to get `provider` parameter, and if it's not where, it founds `sonata.media.provider.image` and throws
```
An exception has been thrown during the rendering of a template ("The product definition `sonata.media.provider.image` does not exist!").
```

**Comment by ZRazor** [comment]
When we open `http://127.0.0.1:8000/admin/sonata/product/product/create` we can choose a product provider and go to `http://127.0.0.1:8000/admin/sonata/product/product/create?provider=PRODUCT_PROVIDER` and this is the only case when we need to detect class by `provider=PRODUCT_PROVIDER` parameter. In all other cases it's correctly detected by `AbstractAdmin::getClass()`

**Comment by jordisala1991** [comment]
That provider parameter is specific to ecommerce or it is the generic parameter when it is an abstract class? Because maybe this could be solved at SonataAdmin level?

**Comment by ZRazor** [comment]
It's specific for ecommerce.
Also it's used in media-bundle but a bit differently https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Admin/BaseMediaAdmin.php#L81
