### ISSUE TITLE
Stable release for Symfony 3.x and 4.x

### ISSUE THREAD

**Issue by slince** [sonata-project/ecommerce#531]
This is an amazing project; when will the stable version for symfony 3.x be released?

**Comment by kunicmarko20** [comment]
We don't know really, `master` branch has support for symfony ^3.x and we will probably release a new Major at some point. You can try using `master` branch and help us with fixing it if anything is broken.

**Comment by jordisala1991** [comment]
There are some things like the integration with the UserBundle that is broken at the moment on master branch

**Comment by slince** [comment]
Thanks!  I have used the master to try it, but I found that the official website's documentation is old, so I don't know what to do next. 

Maybe the document should be updated; it doesn't need to be too detailed. Simply write about the basics of getting started.

**Comment by OskarStark** [comment]
User Bundle is now stable and released.
