### ISSUE TITLE
Error during install - Failed to run, probably memory issue

### ISSUE THREAD

**Issue by Matthew2D** [sonata-project/ecommerce#533]
### Environment

Ubuntu 16.04, Apache2

#### Sonata packages

Just the ecommerce package. 

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```
Did not use composer

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
Did not use composer

#### PHP version

```
$ php -v
# Put the result here.
```
PHP 7.0.28

## Subject

When I run `php bin/load_data.php` I get the following error message. 

`KO Fail to run: /usr/bin/php7.0 -d memory_limit=-1 ./bin/sonata-check.php`

I figured it was do to a memory limit in php.ini. I set the memory_limit to 1024M in both the normal php.ini and the php-cli php.ini and the error still occurs. I'm on digitalocean with a 2gb ram droplet, so I tried upgrading to 3gb, and the problem still happens.

## Steps to reproduce

All I did was follow the _quick_ installation instructions from the official website. 
https://sonata-project.org/get-started

## Expected results

The expected result is to have the script. up and running.

## Actual results

Here is the full output from the command.

> Resetting demo, this can take a few minutes
> - Checking Sonata Project's requirements................................KO
>Fail to run: /usr/bin/php7.0 -d memory_limit=-1 ./bin/sonata-check.php
>OK  gd is installed
>OK  gd with jpg support is installed
>OK  gd with png support is installed
>OK  php-intl extension is installed
>OK  Successfully valid Symfony2's requirements
>OK  mb_strlen() is available
>OK  PDO is available
>OK  PDO mysql is available
>OK  bcmath extension is available
>OK  curl extension is available
>KO  xdebug is not available

> Failed to validate mandatory requirements
> If the error is coming from the sandbox,
> please report the issue to https://github.com/sonata-project/sandbox/issues
> An error occurs when running a command!

Any help would be greatly appreciated. Thank you!

**Comment by jordisala1991** [comment]
This issue should be reopened on sandbox because that is waht you are trying to install.

The error you are getting is because you dont have xdebug installed.
I dont recommend you to use the quick start guide, it is pretty outdated. Each bundle you want to use already has its own install guide, just start with docs of admin bundle.

Anyway just in case, I will link you the sandbox github: https://github.com/sonata-project/sandbox
