### ISSUE TITLE
Serializer is not optional

### ISSUE THREAD

**Issue by core23** [sonata-project/ecommerce#544]
The `serializer` as an optional dependency, but when creating new products using the `sonata:product:generate` command, the `*ProductProvider` class needs a serializer.

**Comment by core23** [comment]
It's not a `require`d dependency: 
https://github.com/sonata-project/ecommerce/blob/2.x/composer.json#L70

**Comment by greg0ire** [comment]
Maybe the use of this command is considered optional too?

**Comment by OskarStark** [comment]
But creating a new Product is only required in dev mode, isn’t it?

**Comment by core23** [comment]
AFAIK you have to generate any product first

**Comment by OskarStark** [comment]
Hmm, what does the git history say?
