### ISSUE TITLE
Unable to install sonata/ecommerse on Symfony 4.1

### ISSUE THREAD

**Issue by kotow** [sonata-project/ecommerce#548]
Unable to install sonata/ecommerse on Symfony 4.1

composer require sonata-project/ecommerce:dev-master        
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - egeloen/ckeditor-bundle 6.0.x-dev requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 6.0.1 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 6.0.0 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 5.0.3 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 5.0.2 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 5.0.1 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 5.0.0 requires symfony/dependency-injection ^2.7|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.6 requires symfony/dependency-injection ^2.2|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.5 requires symfony/dependency-injection ^2.2|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.4 requires symfony/dependency-injection ^2.2|^3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.3 requires symfony/dependency-injection ~2.2|~3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.2 requires symfony/dependency-injection ~2.2|~3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.1 requires symfony/dependency-injection ~2.2|~3.0 -> no matching package found.
    - egeloen/ckeditor-bundle 4.0.0 requires symfony/dependency-injection ~2.2|~3.0 -> no matching package found.
    - sonata-project/ecommerce dev-master requires sonata-project/formatter-bundle ^3.4 -> satisfiable by sonata-project/formatter-bundle[3.4.0, 3.4.1, 3.5.0, 3.x-dev].
    - sonata-project/formatter-bundle 3.4.0 requires egeloen/ckeditor-bundle ^4.0 || ^5.0 -> satisfiable by egeloen/ckeditor-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 5.0.0, 5.0.1, 5.0.2, 5.0.3].
    - sonata-project/formatter-bundle 3.4.1 requires egeloen/ckeditor-bundle ^4.0 || ^5.0 -> satisfiable by egeloen/ckeditor-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 5.0.0, 5.0.1, 5.0.2, 5.0.3].
    - sonata-project/formatter-bundle 3.5.0 requires egeloen/ckeditor-bundle ^4.0 || ^5.0 || ^6.0 -> satisfiable by egeloen/ckeditor-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 6.0.0, 6.0.1, 6.0.x-dev].
    - sonata-project/formatter-bundle 3.x-dev requires egeloen/ckeditor-bundle ^4.0 || ^5.0 || ^6.0 -> satisfiable by egeloen/ckeditor-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 6.0.0, 6.0.1, 6.0.x-dev].
    - Installation request for sonata-project/ecommerce dev-master -> satisfiable by sonata-project/ecommerce[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by jo66** [comment]
I face the same problem but with less composer problems:
> Using version ^2.2 for sonata-project/ecommerce
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.1.*"
Your requirements could not be resolved to an installable set of packages.

> Problem 1
    - Installation request for sonata-project/ecommerce ^2.2 -> satisfiable by sonata-project/ecommerce[2.2.0].
    - sonata-project/ecommerce 2.2.0 requires symfony/config ^2.8 -> no matching package found.

> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> - It's a private package and you forgot to add a custom repository to find it

> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

> Installation failed, reverting ./composer.json to its original content.

Steps to reproduce (Ubuntu 16.04 with php 7.2):
1. Run `composer create-project symfony/website-skeleton sonata-sandbox`
2. Run `cd sonata-sandbox`
3. Run `composer require sonata-project/ecommerce`

**Comment by quisse** [comment]
@kotow This has to do with https://github.com/sonata-project/ecommerce/issues/531
@jo66 OP is trying to install the dev-master branch while you are trying the latest release.

**Comment by wbloszyk** [comment]
@greg0ire this Issue can be close
