### ISSUE TITLE
ProductBundle - The file "command.xml" does not exist 

### ISSUE THREAD

**Issue by salamichel** [sonata-project/ecommerce#597]
#### Sonata packages
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.53.0             = 3.53.0
sonata-project/block-bundle              3.18.1             = 3.18.1
sonata-project/cache                     2.0.1              = 2.0.1
sonata-project/classification-bundle     3.9.0              = 3.9.0
sonata-project/comment-bundle            3.1.1              = 3.1.1
sonata-project/core-bundle               3.17.0             = 3.17.0
sonata-project/datagrid-bundle           2.5.0              ~ 3.0.0
sonata-project/doctrine-extensions       1.3.1              = 1.3.1
sonata-project/doctrine-orm-admin-bundle 3.10.0             = 3.10.0
sonata-project/easy-extends-bundle       2.5.0              = 2.5.0
sonata-project/ecommerce                 dev-master 299ad33 = dev-master 299ad33
sonata-project/exporter                  2.0.1              = 2.0.1
sonata-project/formatter-bundle          4.1.3              = 4.1.3
sonata-project/intl-bundle               2.7.0              = 2.7.0
sonata-project/media-bundle              3.20.1             = 3.20.1
sonata-project/media-orm-pack            1.0.0              = 1.0.0
sonata-project/notification-bundle       3.6.2              = 3.6.2
sonata-project/seo-bundle                2.7.0              = 2.7.0
sonata-project/timeline-bundle           3.4.0              = 3.4.0
sonata-project/user-bundle               4.5.0              = 4.5.0

#### Symfony packages
$  composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.3.*"
symfony/apache-pack                v1.0.1  = v1.0.1  A pack for Apache supp...
symfony/asset                      v4.3.4  = v4.3.4  Symfony Asset Component
symfony/cache                      v4.3.4  = v4.3.4  Symfony Cache componen...
symfony/cache-contracts            v1.1.5  = v1.1.5  Generic abstractions r...
symfony/config                     v4.3.4  = v4.3.4  Symfony Config Component
symfony/console                    v4.3.4  = v4.3.4  Symfony Console Component
symfony/debug                      v4.3.4  = v4.3.4  Symfony Debug Component
symfony/dependency-injection       v4.3.4  = v4.3.4  Symfony DependencyInje...
symfony/doctrine-bridge            v4.3.4  = v4.3.4  Symfony Doctrine Bridge
symfony/dotenv                     v4.3.4  = v4.3.4  Registers environment ...
symfony/event-dispatcher           v4.3.4  = v4.3.4  Symfony EventDispatche...
symfony/event-dispatcher-contracts v1.1.5  = v1.1.5  Generic abstractions r...
symfony/expression-language        v4.3.4  = v4.3.4  Symfony ExpressionLang...
symfony/filesystem                 v4.3.4  = v4.3.4  Symfony Filesystem Com...
symfony/finder                     v4.3.4  = v4.3.4  Symfony Finder Component
symfony/flex                       v1.4.6  = v1.4.6  Composer plugin for Sy...
symfony/form                       v4.3.4  = v4.3.4  Symfony Form Component
symfony/framework-bundle           v4.3.4  = v4.3.4  Symfony FrameworkBundle
symfony/http-foundation            v4.3.4  = v4.3.4  Symfony HttpFoundation...
symfony/http-kernel                v4.3.4  = v4.3.4  Symfony HttpKernel Com...
symfony/inflector                  v4.3.4  = v4.3.4  Symfony Inflector Comp...
symfony/intl                       v4.3.4  = v4.3.4  A PHP replacement laye...
symfony/maker-bundle               v1.13.0 = v1.13.0 Symfony Maker helps yo...
symfony/mime                       v4.3.4  = v4.3.4  A library to manipulat...
symfony/options-resolver           v4.3.4  = v4.3.4  Symfony OptionsResolve...
symfony/polyfill-intl-icu          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-intl-idn          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-mbstring          v1.12.0 = v1.12.0 Symfony polyfill for t...
symfony/polyfill-php72             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/polyfill-php73             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/process                    v4.3.4  = v4.3.4  Symfony Process Component
symfony/profiler-pack              v1.0.4  = v1.0.4  A pack for the Symfony...
symfony/property-access            v4.3.4  = v4.3.4  Symfony PropertyAccess...
symfony/property-info              v4.3.4  = v4.3.4  Symfony Property Info ...
symfony/routing                    v4.3.4  = v4.3.4  Symfony Routing Component
symfony/security-acl               v3.0.2  = v3.0.2  Symfony Security Compo...
symfony/security-bundle            v4.3.4  = v4.3.4  Symfony SecurityBundle
symfony/security-core              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-csrf              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-guard             v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-http              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/service-contracts          v1.1.6  = v1.1.6  Generic abstractions r...
symfony/stopwatch                  v4.3.4  = v4.3.4  Symfony Stopwatch Comp...
symfony/swiftmailer-bundle         v3.2.8  = v3.2.8  Symfony SwiftmailerBundle
symfony/templating                 v4.3.4  = v4.3.4  Symfony Templating Com...
symfony/translation                v4.3.4  = v4.3.4  Symfony Translation Co...
symfony/translation-contracts      v1.1.6  = v1.1.6  Generic abstractions r...
symfony/twig-bridge                v4.3.4  = v4.3.4  Symfony Twig Bridge
symfony/twig-bundle                v4.3.4  = v4.3.4  Symfony TwigBundle
symfony/validator                  v4.3.4  = v4.3.4  Symfony Validator Comp...
symfony/var-dumper                 v4.3.4  = v4.3.4  Symfony mechanism for ...
symfony/var-exporter               v4.3.4  = v4.3.4  A blend of var_export(...
symfony/web-profiler-bundle        v4.3.4  = v4.3.4  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.4  = v4.3.4  Symfony WebServerBundle
symfony/yaml                       v4.3.4  = v4.3.4  Symfony Yaml Component

#### PHP version
$ php -v
PHP 7.2.18 (cli) (built: Apr 30 2019 23:32:39) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

## Subject
1. Last commit introduce  "command.xml"
https://github.com/sonata-project/ecommerce/commit/0b90521926968d7d194a012b01413ea6648b33a4#diff-6c03ebca9553b27367a427923ead880cR43
ProductBundle - The file "command.xml" does not exist 

2. By the way  "bin/console sonata:product:generate" is not available in the console

## Steps to reproduce
bin/console cache:clear --env=dev
 // Clearing the cache for the dev environment with debug
 // true
In FileLocator.php line 71:
  The file "command.xml" does not exist (in: vendor\so
  nata-project\ecommerce\src\ProductBundle\DependencyInjection/../Resources/c
  onfig).

**Comment by core23** [comment]
Can you try to provide a PR with a fix. 

It's [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Comment by salamichel** [comment]
hi, i do not familliar and do not know well the Sonata Ecommercebundle.
sorry can't provide fix

**Comment by salamichel** [comment]
@core23 i have found the solution, i have created PR https://github.com/sonata-project/ecommerce/pull/598 - not sure that the right way.

not able to push on repo

Fatal: AggregateException encountered.
Username for 'https://github.com': salamichel
remote: Permission to sonata-project/ecommerce.git denied to salamichel.
fatal: unable to access 'https://github.com/sonata-project/ecommerce.git/': The                                 requested URL returned error: 403
