### ISSUE TITLE
ProductBundle:CollectionController calls non existent function 'getProductsByCollectionIdPager'

### ISSUE THREAD

**Issue by jeroendk** [sonata-project/ecommerce#618]
# Environment

#### Sonata packages

```
sonata-project/ecommerce  dev-master
```

## Subject
As reported in #322 the CollectionController calls the non-existend function getProductsByCollectionIdPager on the `Sonata\ProductBundle\Entity\ProductSetManager`.

In addition, the ProductSetManager class does not add any actual functionalities, it only throws some RuntimeExceptions for some of the inherited methods and all other calls to this manager are handled by the ProductManager.   So before creating a PR to fix this bug, it would help to know the purpose of the `Sonata\ProductBundle\Entity\ProductSetManager`. 

If no one missed this controller action for the past four/five years it may be dropped altogether?
If not this action could (almost) be handled with the use of the existing method `queryInSameCollections` I think, but that one is also in the ProductManager so no need for the ProductSetManager there. 

## Steps to reproduce
Call SonataProductBundle:Collection:listProducts

## Expected results
List of products within a collection

## Actual results
```
Fatal error: Call to undefined method Sonata\ProductBundle\Entity\ProductSetManager::getProductsByCollectionIdPager() in \vendor\sonata-project\ecommerce\src\ProductBundle\Controller\CollectionController.php 
```

**Comment by jeroendk** [comment]
Is it acceptable to drop the entire CollectionController?
None of the actions works because the needed templates are just not there. 
Also, all the actions are related to listing products in a collection, the CategoryController does not provide these functions so why should the CollectionController?

**Comment by greg0ire** [comment]
cc @salamichel @pierredup @quisse . BTW folks, it would be great if all of you click the "watch" button on this repository, a lot of you contribute, and might feel a bit lonely when doing so, answering to each other would help a lot.

That said, I'm personally ok with dropping the entire `CollectionController`. Everything that is not perfectly understood should not stay IMO, so either someone explains the situation or they remove it.

**Comment by salamichel** [comment]
I prefer to say CollectionController should work correctly :o). i'm not ready to discuss deeper on this fonctionnality but as i saw there are no routes to access actions of CollectionController. Please do not drop CollectionController right now.

@jeroendk how you access to `SonataProductBundle:Collection:listProducts` there are no defined routes related to this listProductsAction  :/

**Comment by jeroendk** [comment]
@salamichel Someone may add the routes themselves like in #322. Nevertheless all of the actions in the Collection controller use templates that do not exist.

**Comment by salamichel** [comment]
yes indeed, so we have to add all necessaries objects to make it works. \o/

**Comment by jeroendk** [comment]
Yes but still:

- Almost no one missed these actions for the past 5 years (it never worked). 
- It is inconsistent with the CategoryController, the CategoryController does not provide methods for showing the products inside.
- Maintaining this bundle and keeping it up to date seems hard enough on its own. Should we really focus on broken (unused) functions that are in the code since the first release or on functions that are actually being used?

**Comment by wbloszyk** [comment]
### For delete:
1. CollectionController are unused 
1. CollectionController try use not existing methods like ProductCollectionManager->getSubCollectionsPager.
1. Collections structure in CollectionController look like tree structure (self-referencing), but it is not (look at SonataClassificationBundle:Collection)

### For not delete:
1. Nice to have page for display all collection products (not only block)
1. Add some feature(maybe discount) for collection and display collections list (collection have media)

### Lets drop
- listSubCollectionsAction
- listSideMenuCollectionsAction

### And fix
- indexAction
- viewAction, listProductsAction (it similar, mybe merge?)

### Collection are used in (without CollectionController):
- Children admin for ProductAdmin
- Product show page (block type: "sonata.product.block.similar_products")
- ProductManager and ProductFinder
