### ISSUE TITLE
Admin Product List

### ISSUE THREAD

**Issue by mgomez-dgt** [sonata-project/ecommerce#9]
http://{host}/admin/sonata/product/product/list

An exception occurred while executing 'SELECT count(DISTINCT p0_.id) AS sclr0 FROM product__product p0_ LEFT JOIN product__product_category p1_ ON p0_.id = p1_.product_id LEFT JOIN classification__category c2_ ON p1_.category_id = c2_.id LEFT JOIN product__product_collection p3_ ON p0_.id = p3_.product_id LEFT JOIN classification__collection c4_ ON p3_.collection_id = c4_.id WHERE p0_.product_type IN ()':

**Comment by pguso** [comment]
@emmanuel-tesson i had the same problem and find a really good post with the solution http://stackoverflow.com/questions/26049290/using-discriminator-in-a-entity-that-extends-another

**Comment by utkarsh2k2** [comment]
@mgomez-dgt I followed the steps you showed, still get the same error. Also when I click on "Add new" product, I get blank page with no fields. Could you look into the issue please?
